version: "3.9"

services:
  project: # smalll letter default image name
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./Multi-Vendor-Hospital-System:/Multi-Vendor-Hospital-System:z
    #user: user1
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - CACHE_URL=redis://redis:6379/1 

    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres:14-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
  
  redis:
    image: redis:7-alpine
    command: redis-server
  


  celery_worker:
    build:
      context: .
    image: vendor_celery_worker
    command: celery -A Multi_Vendor_Hospital_System worker --loglevel=info
    volumes:
      - ./Multi-Vendor-Hospital-System:/Multi-Vendor-Hospital-System
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

    depends_on:
      - db
      - redis

  celery_beat:
    build:
      context: .
    image: vendor_celery_beat
    command: celery -A Multi_Vendor_Hospital_System beat
    volumes:
      - ./Multi-Vendor-Hospital-System:/Multi-Vendor-Hospital-System
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      
      
  celery_flower:
    build:
      context: .
    image: vendor_celery_flower
    command: celery -A Multi_Vendor_Hospital_System flower --port=5555
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    
    ports:
      - 5555:5555
    depends_on:
      - redis
      - project
      - celery_worker

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
      
volumes:
  dev-db-data:  
  es-data: 
