# Generated by Django 4.2.5 on 2023-10-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorappointment",
            name="serial_no",
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
