# Generated by Django 4.2.5 on 2023-10-12 06:47

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=versatileimagefield.fields.VersatileImageField(
                default="placeholder/man.jpg",
                upload_to="headshots/",
                verbose_name="Headshot",
            ),
        ),
    ]
