# Generated by Django 4.2.5 on 2023-10-27 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Hospital", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorschedule",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Hospital.hospital"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="doctor_info",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="doctorspecialtyconnector",
            unique_together={("doctor", "specialty")},
        ),
    ]
