# Generated by Django 4.2.5 on 2023-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="logo",
            field=models.ImageField(blank=True, upload_to="hospital_logos/"),
        ),
    ]
